SELECT 
	nu.*,
    sum(ntb.Documentaries) AS Documentary,
    sum(ntb.NA) AS Unlisted,
    sum(ntb.InternationalTVShows) AS InternationalTVShow,
    sum(ntb.TVDramas) AS TVDrama,
    sum(ntb.TVMysteries) AS TVMystery,
    sum(ntb.CrimeTVShows) AS CrimeTVShow,
    sum(ntb.TVActionAdventure) AS TVActionAdventure,
    sum(ntb.Docuseries) AS Docuseries,
    sum(ntb.RealityTV) AS RealityTV,
    sum(ntb.RomanticTVShows) AS RomanticTVShow,
    sum(ntb.TVComedies) AS TVComedy,
    sum(ntb.TVHorror) AS TVHorror,
	sum(ntb.ChildrenFamilyMovies) AS ChildrenFamily,
    sum(ntb.Dramas) AS Drama,
    sum(ntb.IndependentMovies) AS Indie,
    sum(ntb.InternationalMovies) AS InternationalMovie,
    sum(ntb.BritishTVShows) AS BritishTVShow,
    sum(ntb.Comedies) AS Comedy,
    sum(ntb.SpanishLanguageTVShows) AS SpanishTVShow,
    sum(ntb.Thrillers) AS Thriller,
    sum(ntb.RomanticMovies) AS RomanticMovie,
    sum(ntb.MusicMusicals) AS Musical,
    sum(ntb.HorrorMovies) AS HorrorMovie,
    sum(ntb.SciFiFantasy) AS SciFiFantasy,
    sum(ntb.TVThrillers) AS TVThriller,
    sum(ntb.KidsTV) AS KidsTV,
    sum(ntb.ActionAdventure) AS ActionAdventure,
    sum(ntb.TVSciFiFantasy) AS TVSciFiFantasy,
    sum(ntb.ClassicMovies) AS Classic,
    sum(ntb.AnimeFeatures) AS AnimeFeature,
    sum(ntb.SportsMovies) AS SportMovie,
    sum(ntb.AnimeSeries) AS AnimeSeries,
    sum(ntb.KoreanTVShows) AS KoreanTVShow,
    sum(ntb.ScienceNatureTV) AS ScienceNatureTV,
    sum(ntb.TeenTVShows) AS TeenTVShow,
    sum(ntb.CultMovies) AS CultMovie,
    sum(ntb.TVShows) AS TVShows,
    sum(ntb.FaithSpirituality) AS Faith,
    sum(ntb.LGBTQMovies) AS LGBTQMovie,
    sum(ntb.StandUpComedy) AS StandUp,
    sum(ntb.Movies) AS Movie,
    sum(ntb.StandUpComedyTalkShows) AS StandUpTalkShow,
    sum(ntb.ClassicCultTV) AS ClassicCultTV
FROM 
	netflix.netflix_users nu,
	netflix_sessions ns,
	netflix_title_binary ntb
WHERE 
	nu.ID = ns.UserID
AND
	ns.ShowID = ntb.show_id
GROUP BY nu.ID;